### ISSUE TITLE
Best way to display frames from VideoCapture (as a video stream) and process it?

### ISSUE THREAD

**Issue by fildaniels** [justadudewhohacks/opencv4nodejs#111]
Hey,
To your mind, what is the best solution to continuously display (imshow) each frame from a VideoCapture with the minimum latency by applying asynchronously a detection process (whatever : face, pedestrian, etc...) and display the result of each processed frame in the same stream ? Separate grabbing and decoding in 2 different threads ? If so, what is the best way to do it with opencv4nodejs ? 
Many thanks for your very cool module!
fildaniels

**Comment by justadudewhohacks** [comment]
Hey, 

first of all I would **not** recommend grabbing the frames from the same capture in parallel. I did not try this for with a webcam, but grabbing from a video files from different threads always gave me an exception from the decoding library, which complains about not being able to get the lock. In #98 @cotejp apparently did use `vCap.asyncRead()` with a single capture from a webcam, I am not sure if that actually works without problems.

I would rather grab the frames from the main thread. You could then just do all the detection stuff with async functions on let's say 4 different threads or something. When a thread finishes, display the frame or buffer it somewhere. I would also give each frame an id, which you can pass to a callback when a thread finishes in order to keep the order of frames, as I can not guarantee, that the threads are finishing in order.

For displaying a frame I would just use something like:
```
cv.imshow('drawImg', drawImg)
cv.waitKey(1)
```
waitKey(0) will not work as this is waiting for a keypress. Simply waitKey for 1ms, shouldn't hurt that much.

**Comment by cotejp** [comment]
> In #98 @cotejp apparently did use vCap.asyncRead() with a single capture from a webcam, I am > not sure if that actually works without problems.

It works great! Actually, the real bottleneck is my webcam's relatively low bandwidth (USB2). I believe the webcam's max throughput is 30FPS in HD (1280x720). My app is running at 30'ish frames per second but is mostly waiting on data from the cam.

I'm using `asyncRead()` to read a frame. The detection is performed inside the callback function. The processed image is then displayed on canvas (I'm using NW.js). Once it's done, I just start over. It's a very naive approach but it works perfectly for my needs. I guess you could do the same with `imshow()` instead of the canvas.

**Comment by fildaniels** [comment]
Thanks a lot justadude for your advices and codejp for sharing experiments ... I'll give a try to NW.js 
fil
