### ISSUE TITLE
question about perspectiveTransform

### ISSUE THREAD

**Issue by Gektor40k** [justadudewhohacks/opencv4nodejs#161]
Hello!
In the c++ code which I'm porting to node.js, using function:
` CV_EXPORTS_W void perspectiveTransform (InputArray src, OutputArray dst, InputArray m) `
(from core.hpp) - I tried to find an analog of this function in opencv4nodejs, but there is only perspectiveTransform, which is a function of Mat class. 
There are other arguments and the result of the work. 
Can I find a suitable option, or it does not exist?

**Comment by justadudewhohacks** [comment]
For any function, if the first argument is the source mat itself, then the function will be part of the Mat instance. Also outputs are usually always returned in opencv4nodejs and never passed as arguments. 

Thus perspectiveTransform will translate to:
`const dst = src.perspectiveTransform(m)`

Hope this clarifies it.

**Comment by Gektor40k** [comment]
Thank you, i think its should work! 
Then the additional question, unfortunately, could not find information about it. 
`InputArray src` is not Mat, it is an array of Point2. 
Can I make a new Mat from this array? What constructor or function should I use?

**Comment by justadudewhohacks** [comment]
Yes, I think in general in OpenCV you can represent a std::vector of Points and Vecs (or Arrays of Points and Vecs in case of Javascript) as Mats.

It will probably look somehow like this in case of Point2:

As a 1D 2-channel matrix:
``` javascript
const matData = [
  points.map(pt => [pt.x, pt.y])
]

const src = new cv.Mat(matData, cv.CV_32FC2)
```

As a 2D 1-channel matrix:
``` javascript
const matData = [
  [], // array with x coordinates
  [] // array with y coordinates
]
points.forEach(pt => { 
  matData[0].push(pt.x); 
  matData[1].push(pt.y) 
})

const src = new cv.Mat(matData, cv.CV_32FC1)
```

Not sure which one is the correct way to do it.

**Comment by Gektor40k** [comment]
Yes! Thank you! All is working!

**Comment by woojoo666** [comment]
neither method is working for me. I tried

```js
const matData = [
  [0, 0],
  [10, 0],
  [10, 20],
  [20, 20]
];
const srcCorners = new cv.Mat(matData, cv.CV_32FC2)
const dstCoordinates = srcCorners.perspectiveTransform(homography)
```
and this silently fails (exits without getting to the last line, perspectiveTransform() is never called).
I believe the matrix type CV_32FC2 is the problem, because I can create CV_32F matrices without issue.

If I try the other method:

```js
const matData = [
  [0, 10, 10, 0], // array with x coordinates
  [0, 0, 20, 20] // array with y coordinates
];
const srcCorners = new cv.Mat(matData, cv.CV_32FC1)
const dstCoordinates = srcCorners.perspectiveTransform(homography)
```

this one gives me the error:

```
const dstCoordinates = srcCorners.perspectiveTransform(homography)
                                  ^
Mat::PerspectiveTransform - OpenCV Error: (scn + 1 == m.cols) in cv::perspectiveTransform, in file C:\build\master_winpack-build-win64-vc15\opencv\modules\core\src\matmul.cpp, line 2268, status -215
```

Could you help me out? I'm really having trouble finding any sort of documentation on this stuff.

**Comment by justadudewhohacks** [comment]
Hi, 

Regardless from the first error, I am not quite sure but I think perspectiveTransform expects a 4x4 single channel Matrix, doesn't it?

The reason why you can't create a Mat with `CV_32FC2 ` is because you provide it data with values for a single channeled Mat. For a 2 channel Mat it would be something like this:

``` javascript
const matData = [
  [ [0, 0] , [0, 0] ],
  [ [10, 10], [0, 0] ],
  [ [10, 10], [20, 20] ],
  [ [20, 20], [20, 20] ]
];
```

**Comment by woojoo666** [comment]
isn't that what I did?

```js
const matData = [
  [0, 0],
  [10, 0],
  [10, 20],
  [20, 20]
];
const srcCorners = new cv.Mat(matData, cv.CV_32FC2)
const dstCoordinates = srcCorners.perspectiveTransform(homography)
```

is this not creating a 1D 2-channel matrix, and then calling perspectiveTransform on it? What am I doing wrong?

**Comment by justadudewhohacks** [comment]
No, in your example you are creating a Matrix with 4 rows, 2 columns each (4x2) Matrix, with flat values (single channeled).

**Comment by justadudewhohacks** [comment]
According to http://answers.opencv.org/question/110408/assertion-failed-scn-1-mcols/, this might be due to your homography being empty.

How do you actually calculate the homography? If you are using `cv.findHomography` then you should input an array of source and an array of destination points `cv.findHomography(srcPoints, dstPoints)` as stated here: https://opencv4nodejs.herokuapp.com/docs/calib3d#findHomography

**Comment by woojoo666** [comment]
I only modified the matchFeatures.js example a tiny bit.

[Here is my code](https://gist.github.com/woojoo666/de66e3d56b9e5b30258448c2e0e00be7)
And [here is a diff](https://www.diffchecker.com/9zb0QO50) between matchFeatures.js and my code

**Comment by justadudewhohacks** [comment]
Hmm, sorry I am not familar with how exactly the source Matrix for perspectiveTransform has to look like. But from the docs it looks like they should accept 2D or 3D vectors. Also it would be probably better to accept an array of Vec2 or Vec3 instead of a Matrix here in the implementation of the binding.

**Comment by amberneil** [comment]
Just wanted to chime in here, I've struggled with this problem for a day or so.  

It didn't end up being an empty homography result, which is the diagnosis all over Google, it was my formatting of the matrix that you have labelled "matData" in https://github.com/justadudewhohacks/opencv4nodejs/issues/161#issuecomment-383359698. This structure worked for me:

```javascript
const matData = [
    [[0, 0]],
    [[10, 0],
    [[10, 20]],
    [[20, 20]],
];
const srcCorners = new cv.Mat(matData, cv.CV_32FC2);
const dstCoordinates = srcCorners.perspectiveTransform(homography);
```
The nested arrays take a minute to wrap your head around, and the cv.CV_32FC2 parameter tripped me up for a long time. Any other type than cv.CV_32FC2 gave me the "OpenCV Error: (scn + 1 == m.cols)".

**Comment by rainabba** [comment]
@justadudewhohacks I'm learning my way around homography (for form/image alignment) and was excited to see https://opencv4nodejs.herokuapp.com/docs/calib3d#findHomography, but the app looks to be dead. Will that be coming back?

**Comment by rainabba** [comment]
@woojoo666 I'm still stuck on using findHomography(). Mind sharing your implementation for us to learn from?

**Comment by saadshahd** [comment]
@justadudewhohacks How to extract the dest XY from the result matrix?
