### ISSUE TITLE
how to invoke webcamFaceDetectionCpu.js from HTML

### ISSUE THREAD

**Issue by vijaysagi** [justadudewhohacks/opencv4nodejs#176]
To invoke the specified .js from html i tried by installing express.js module but i could not figure out the steps.

In this regard i have two questions:

Q 1) pls suggest the steps required to invoke the webcamFaceDetectionCpu.js from html file
Q 2) pls let me know how to save the detected face as image.

Thanks

**Comment by justadudewhohacks** [comment]
First to grab frames from your webcam in the browser use the getUserMedia API. Then use websockets (socket.io) to stream the images to a nodejs server. On the server then create a Mat from the bytestream and invoke face detection as done in the example.

If you want to save the image as a file on your backend, simply use cv.imwrite. Otherwise encode the result image (cv.imencode) and send the base64 string back to the client, where you can display it or save it using the browsers API.
