### ISSUE TITLE
Missing functions and more

### ISSUE THREAD

**Issue by asilvas** [justadudewhohacks/opencv4nodejs#192]
Howdy. Any intent to add support for any of the missing cv features?

I'm sure there are more, these are just the ones I found from my usage:

```
INTER_LINEAR_EXACT
Mat::push_back
merge
split - Moved to Mat::splitChannels ?
cartToPolar
polarToCart
resize - Seems to be comparable alternative under Mat::resize
cvtColor - Seems to be comparable alternative under Mat::cvtColor
```

Seems many root level `cv::` functions were moved to classes. Not sure if it was preference or necessity, but makes translating existing cv code more difficult since opencv.org has all the docs. Suggestions?

**Comment by justadudewhohacks** [comment]
Hi,

I will answer your second question first:

Yes indeed, the API slightly differs from the original opencv API, such that a signature like: `cv.functionName(inputMat, outputMat, foo, bar)` becomes: `outputMat = inputMat.functionName(foo, bar)`. This is mainly a design decision I made initially, as some concepts do not translate well into the javascript world in my opinion (for example passing pointers to return values as arguments to a function calls)

Furthermore, this allows you to conveniently chain function calls. Instead of writing code like this:
``` javascript
cv.cvtColor(in, out1, ...)
cv.threshold(out1, out2, ...)
cv.blur(out2, result, ...)
```

You can chain operations:
``` javascript
const result = in.cvtColor(...).threshold(...).blur(...)
```

I agree, that this might make it inconvenient to convert existing OpenCV code from C++ or python to javascript, but by simply looking up the method signature in the [docs](https://opencv4nodejs.herokuapp.com/docs/) it should be possible easily, in my opinion.

To the first question:

`splitChannels` (should of probably just called it split), `resize` and  `cvtColor` are accessible from the Mat object, as you figured out already. 

`merge` is equivalent to calling the constructor with `new Mat([channel1, channel2, channel3])` (see Mat constructor: `Mat : new Mat ( [ Mat ] channels )`.

`cartToPolar` , `polarToCart` and `push_back` are apparently not implemented yet (as mentioned in the other issue, the package is not complete). `INTER_LINEAR_EXACT` is a flag I guess? Looks like the flag has just been added in one of the previously released OpenCV versions (probably 3.4.1) and needs to be added to the package.

**Comment by asilvas** [comment]
Makes sense, I'm quickly finding through usage it works quite well. I'll work around the other items for now as I'm hopeful this library will become the defacto opencv node package. Many thanks for the detailed response and great work!

**Comment by justadudewhohacks** [comment]
Just added `INTER_LINEAR_EXACT`, `cartToPolar`,  `polarToCart`, `Mat::push_back`.

**Comment by asilvas** [comment]
You rock, thanks much!

**Comment by asilvas** [comment]
Looks like `cv::log` and `cv::exp` are harder to map to js `Math` functions than I expected as their behavior seems specific to `Mat` class. If you get a chance...

**Comment by legraphista** [comment]
Hi! 
I feel like i'm piggybacking on this issue, but by any chance, do you have any plans to also add `cv::goodFeaturesToTrack`? 😄

**Comment by justadudewhohacks** [comment]
`cv::exp` should be available. Will add `cv::log` and `cv::goodFeaturesToTrack` next time I find the time.

**Comment by justadudewhohacks** [comment]
Closing. Thanks to @legraphista `cv::log` and `cv::goodFeaturesToTrack` have been added with #217 and #218 :)

**Comment by rainabba** [comment]
> merge is equivalent to calling the constructor with new Mat([channel1, channel2, channel3]) (see Mat constructor: Mat : new Mat ( [ Mat ] channels ).

I just landed here while searching for [cv.merge](https://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html#void%20merge(const%20Mat*%20mv,%20size_t%20count,%20OutputArray%20dst))

Perhaps an alias to that constructor would make sense to address the expected method and that solution?
