### ISSUE TITLE
Support for OSX

### ISSUE THREAD

**Issue by dudash** [justadudewhohacks/opencv4nodejs#2]
It would be nice to be able to `npm install` on a Mac.  Currently when I try I get this error:

```
node_modules/opencv4nodejs/lib/utils.js:91
```
...
```
Error: no valid '.so' files found in in OPENCV_LIB_DIR ('/usr/local/lib')
```

in looking at the code it's due to libSuffix not recognizing the .dylib file extension of OSX:
```
const libSuffix = process.platform === 'win32' ? '.lib' : '.so';
```

**Comment by justadudewhohacks** [comment]
Hello dudash,

Thanks for reporting this issue. I haven't tried to build it yet for OSX since I don't have access to a Mac and haven't setup a Mac VM yet, which I was planning to do this week though.

I just published a quickfix to support .dylibs, which hopefully fixes your issue. Please let me know if it does or if there are any further issues.
