### ISSUE TITLE
general 'crashability'

### ISSUE THREAD

**Issue by btsimonh** [justadudewhohacks/opencv4nodejs#212]
Not a great deal of thought in this one yet - a starter for discussion.

one thing I've always found with OpenCV is that it's quite easy to kill if you do something wrong.
(Asserts and exceptions tend to kill nodejs dead... in this and other node/opencv projects).

Since most of the functions seem to use something like 'SimpleWorker', I wonder how easy it is to wrap up 'execute' in a try-catch to return an error rather than just die...  i.e. may be useful to scope what would be required in terms of changes.

I'm thinking FF_WORKER_SYNC could be updated to call a wrapper (e.g. _execute) which in turn calls execute in a protected manner. FF_WORKER_ASYNC similarly.  Thus all functions which use this would immediately get the try/catch

getReturnValue may be better as a define, so that that too can be wrapped (or even just have a define which represents the whole 'info.GetReturnValue().Set(worker.getReturnValue());'; this can then be added piecemeal as time allows, so protecting us from the return code failing. 

ideas?

**Comment by justadudewhohacks** [comment]
Yes I like that idea and actually that's what I initially intended to do. I was not sure how to catch the assertion exceptions thrown by OpenCV e.g. if it's possible to catch them and if it's possible to keep the node process alive, after such an exception is thrown.

**Comment by btsimonh** [comment]
https://docs.opencv.org/3.1.0/db/de0/group__core__utils.html
looks like CV_Assert() actually throws a specific exception....  and the general ASSERT() macro should not exist in release builds...
Certainly I've seen different types of deaths; including one which gave a popup MSVC windows dialogue; we probably won't be able to catch everything (without really messing with node).

**Comment by justadudewhohacks** [comment]
Yes the ones you described I have received too, usually when v8 throws an exception. I think this is just some bug in the code (I think some of the Mat construction from JS arrays is still brittle). Atleast v8 exceptions should not occure due to wrong usage of a method interface by the programmer.

Being able to Catch the OpenCV exceptions would be a good start.

I have also seen segmentation faults when using the OpenCv API with aome unexpected input, but that should be rather rare and I think we cant do much about it.

**Comment by justadudewhohacks** [comment]
Just published version 4.2.0. It is now possible to catch and handle OpenCV exceptions, without crashing the node process.

**Comment by wbern** [comment]
@justadudewhohacks That release number seems to be missing from github releases, just FYI.

**Comment by wbern** [comment]
@justadudewhohacks I just sort of caught myself thinking there was no 4.2 update, because github releases these days usually always match the npm releases (which are more annoying to check on the npm site).

Ideeally you'd want to have a proper changelog in the future, where I think the github releases page comes in handy as opposed to only having npm releases. This could be resolved using a simple `CHANGELOG.MD` file I suppose, but I see the trend recently has shifted a lot towards having changelog in the releases page.

Now that I understand you train of thought I don't think it's a huge deal, but it confused me at first not being like the other packages I follow. Perhaps others will feel the same.

**Comment by justadudewhohacks** [comment]
Good point. I think having changelogs would be useful as well, I just was not strict enough yet, with keeping track of changes
