### ISSUE TITLE
setup recommendation

### ISSUE THREAD

**Issue by kostadinnm** [justadudewhohacks/opencv4nodejs#229]
Hello
I've been trying to utilize the lib within an electron app these days. The thing is, I find vs tools too "fat" for the purpose. With a linux virtual machine at hand, I managed to run some tests.
At first I gave a shot at your [face-recognition.js](https://github.com/justadudewhohacks/face-recognition.js), whose FaceDetector.detectFaces(<image>) gave some not so great results. I tried three images - one without any faces, one with a single face and one with 24 faces. The no-face one gave around a second(not sure exactly), but those with faces were 7-to-10 seconds. Moreover, the 24-faces one detected only 3 faces.
Then I added the [opencv4nodejs](https://github.com/justadudewhohacks/opencv4nodejs) package and tried the following:

`const {HAAR_FRONTALFACE_ALT} = cv;`
`const classifier = new cv.CascadeClassifier(HAAR_FRONTALFACE_ALT);`
`//setting imagePath`
`cv.imreadAsync(imagePath)`
`.then(function(result) {`
`        image = result;`
`        return classifier.detectMultiScaleAsync(image);`
`        });`

which gave something around 500-700ms. That is totally acceptable for the app I'm at and it detected all the 24 faces.
I want to go for further testing, but I cannot justify the vs tools size. Moreover, for the app I'm at, it requires a webcam, which only my low-powered laptop has. Loading linux on it is an option, but I'm postponing for now. What's not clear for me as well, is whether this openblas builder frees you from using vs tools and/or cmake?! If that is the case, I'd push some more effort building it on windows. But still, it's so unclear - does it help building opencv4nodejs(which is tremendously heavy - a couple of gigs and 20-40 mins on my most powerful machine) or it just improves face detection/other opencv calculations?!

**Comment by kostadinnm** [comment]
I think it now builds with only those added:
![2018-03-28 17_31_16-visual studio installer](https://user-images.githubusercontent.com/18436405/38039971-224e63e4-32b7-11e8-94e4-0855c1fd40c8.jpg)
![2018-03-28 17_33_30-visual studio installer](https://user-images.githubusercontent.com/18436405/38039973-247f4e08-32b7-11e8-8857-5f15bf17a151.jpg)
It's great that there's an option to `npm install --global windows-build-tools`, but it would be waste of disk space. Moreover, I prefer the build tools to be included in something like chocolatey packages. Those tools have two choco packages, which have some options, but they rather revert to the installer and it's 'modify'-options.
Some side stuff:
-internally you're using opencv-build, which gets triggered every time I add/remove package. It's taking a lot of time, but it's maybe because I'm using yarn instead of npm.
-electron and electron-rebuild could be dev dependencies(in package.json I encounter them as standard ones).

**Comment by justadudewhohacks** [comment]
Hi,

I am sorry, but I do not quite understand the question/s, so I will try to answer step by step:

1. To the question about face-recognition.js vs opencv4nodejs for face detection:

There are two types of FaceDetectors available in face-recognition.js, A) a basic FrontalFaceDetector and B) a FaceDetector working with a neural net. Compared to the opencv4nodejs CascadeClassifier you should obtain more accurate results with B, especially when faces are not perfectly frontal, thus I am surprised that it didn't work out for your 24 faces image. 

Performancewise, you can improve detection speed of B quite a bit by installing openblas as pointed out in the README. However, the opencv4nodejs CascadeClassifier can give you realtime performance (500-700ms is still kind of slow, you can highly reduce this time by providing it a minSize and scaleStep).

2. VS Build Tools:

VS Build Tools are of course only required on windows. Actually you only need the MSVC compiler and the msbuild.exe to generate the solution + for node-gyp. Not sure if this helps you narrowing down the required extensions.

For opencv4nodejs msvc14 (VS 2015 compiler) is sufficient to compile the package. For face-recognition.js a fully c++11 compatible compiler is required to compile some parts of dlib (thus you need msvc15 (VS2017 compiler). Some people use `npm install --global windows-build-tools` for simplicity, some don't it is not required, you can install the build tools from any other source.

On any non windows system a c++11 toolchain should be enough to compile everything.

Cmake is only required by the packages for building with the autobuild script.

With both packages you can **skip** the auto build and use your own installation of opencv or dlib, in case you think you can get away with a lower package size this way.

3. Openblas:

I am not sure what you mean by "openblas builder". As mentioned above, you can install openblas to improve the performance of the FaceDetector and FaceRecognizer of face-recognition.js. This doesn't help you with building any of the packages, it is an additional step, that has to be performed before installing the face-recognition.js.

4.

> Some side stuff:
-internally you're using opencv-build, which gets triggered every time I add/remove package. It's taking a lot of time, but it's maybe because I'm using yarn instead of npm.

Yes, that might be related to yarn then, clearing the opencv build folder, which resides in the node_modules folder of your project. You could workaround this issue by installing the package globally or seperately at any other place and require it from there. Alternatively you can use an own build of opencv or dlib and skip the auto build altogether.

> -electron and electron-rebuild could be dev dependencies(in package.json I encounter them as standard ones).

True. I am not so strict about this, as these are only examples anyways.

Hope I was able to answer some of your questions.

**Comment by kostadinnm** [comment]
1. Here's the 24-face image I'd been using:
![more_faces](https://user-images.githubusercontent.com/18436405/38160101-68294d6a-34c0-11e8-8302-18cf8330e8c9.jpg)
I'm getting traction on the usability of all those libs, so I'll try to make a comparison soon. I think I tried the FrontalFaceDetector, but I was missing something and it didn't build/run. Regarding opencv4nodejs, I plan to stick with defaults as I need some knowledge on the algorithm itself(adjusting minSize and scaleStep). Looking at the [app it's meant to be used in](https://github.com/hovancik/stretchly), I think I shouldn't go that far, but it'd be ideal to tease a friend of mine who's into image processing :) I think there's a discussion to port its functionality to a more lightweight platform - [electrino](https://github.com/pojala/electrino). And I personally seek for a lightweight face detection from the webcam for a kind-of is-use-staring sensor. I went for the native effort - [https://wicg.github.io/shape-detection-api/](https://wicg.github.io/shape-detection-api/), which works great, but found usable in latest chromium 65, while electron is far behind(chromium 59).

2. I think python is needed as well for the electron example(opencv4nodejs). I think on my second machine it wouldn't build without it.
I realise this is not the place, but I'm just getting used to these libs. So, regarding the dlib-based one([face-recognition.js](https://github.com/justadudewhohacks/face-recognition.js)), it asks fro vc++ 2017 toolset v141(which should be the toolchain, I guess), but also a windows SDK as well:

![2018-03-31 09_04_02-shell](https://user-images.githubusercontent.com/18436405/38160309-387f41e2-34c4-11e8-8b35-08884830fce4.jpg)

which require 3.5+ GB:
![2018-03-31 09_13_06-visual studio installer](https://user-images.githubusercontent.com/18436405/38160313-4a95b4c4-34c4-11e8-921c-b1d53bd1cffb.jpg)
The windows SDK alone is 2+GB, and I cannot decide which of the many flavours it has to push for installation?!

3. I'm not that much of a native c/c++ builder guy, more of a web dev, so openblas is last option if the performance is not acceptable. But, yes, I got it - it should help with the performance of the actual detection.

4. I have node LTS, which ships with npm 5.6. I just installed a package called "use-yarn", and to tell you the truth, it'd been much faster on the download-part. It may have used caching. Latest npm may be as fast, but I prefer the most stable node and like yarn as well. The actual build has been as slow as my machine can handle lib the size of opencv :)


Thanks for the answers. I think the issue should be closed in favor of more concrete question(s) on the corresponding repos.
Kudos for the efforts!

Cheers,
Kostadin
