### ISSUE TITLE
Mat.convertTo raise an Exception

### ISSUE THREAD

**Issue by gpanneti** [justadudewhohacks/opencv4nodejs#278]
Hello !

I just reinstall my OS and started a new project, I'm facing an issue with Mat convert.

This code:
`new cv.VideoCapture(0).read().convertTo(cv.COLOR_RGB2GRAY);`

Raise this exception:

`Error Mat::ConvertTo - OpenCV Error: (func != 0) in convertTo in file [...] /node_modules/opencv-build/opencv/opencv/modules/core/src/convert.cpp, line 1333, status -215`

Maybe its because I don't have opencv installed manually but I though that it was totally embedded in the package.

I'm on Ubuntu 18.04.

Thanks in advance !
Guillaume

**Comment by justadudewhohacks** [comment]
Hi,

First of all I would check whether read() returns an empty Mat, which might be the case and skip to the next frame in that case. Also you shouldn't recreate cv.Videocapture on every frame.

If that doesn't help, you could also search for this error message on the OpenCV forums, as it is just a forwarded OpenCV Exception.

**Comment by justadudewhohacks** [comment]
Does it occur immediately or can you read some frames successfully?

Also two things to note here:

1. You are missing the empty check:
`while (!frame || frame.empty)`

2. `convertTo` returns the result and does not touch `frame` itself and by default OpenCV should read images in BGR format instead of RGB, so you probably want something like this:
`const frameGray = frame.convertTo(cv.COLOR_BGR2GRAY);`

Instead of `frame.convertTo(cv.COLOR_BGR2GRAY);` you can also use `frame.bgrToGray()`

**Comment by gpanneti** [comment]
Hello !

Thank you for your help, the problem was that I did RGB2GRAY instead of BGR2GRAY (or the better code `frame.bgrToGray()`.

I should have try this before, thanks again !
