### ISSUE TITLE
kmeans only supports 2 categories

### ISSUE THREAD

**Issue by roelkok** [justadudewhohacks/opencv4nodejs#379]
Hi,

I wanted to do some color quantization using the `kmeans` methods as demonstrated in [this example from the OpenCV docs](https://docs.opencv.org/3.4.1/d1/d5c/tutorial_py_kmeans_opencv.html). But the calculated centers from the opencv4nodejs bindings are `Point2` objects. Meaning the centers only work on 2 channels of the color image. As I understand it, the `kmeans` function of OpenCV should be able to work with more than 2 channels. So the limitation seem to come from the nodejs bindings.

My code
```
const { labels, centers } = cv.kmeans(
    [
        new cv.Vec3(255, 0, 0),
        new cv.Vec3(255, 0, 0),
        new cv.Vec3(255, 0, 255),
        new cv.Vec3(255, 0, 255),
        new cv.Vec3(255, 255, 255)
    ],
    2,
    new cv.TermCriteria(cv.termCriteria.EPS | cv.termCriteria.MAX_ITER, 10, 0.1),
    5,
    cv.KMEANS_RANDOM_CENTERS
);
```
When I run this `centers` will be a `Point2` array while I would expect a `Point3` one.

**Comment by justadudewhohacks** [comment]
Ah yeah, kmeans currently is only implemented for Point2. The reason why it accepts Vec3s is because they happen to have an x and y property, thus are treated as Point2s. The [kmeans binding](https://github.com/justadudewhohacks/opencv4nodejs/blob/8ed4b3bd694c575cfb96eb55452fa3b5fe3c9f3b/cc/core/core.cc#L100), could be adjusted to accept other inputs as well.
