### ISSUE TITLE
Binding issue for KeyPoint.point / KeyPoint.pt

### ISSUE THREAD

**Issue by Volune** [justadudewhohacks/opencv4nodejs#584]
According to type file [KeyPoint.d.ts](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/lib/typings/KeyPoint.d.ts) the attribute is named `point`, but in [KeyPoint.cc](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/features2d/KeyPoint.cc) it is named `pt`.

----
Found when trying to use `opencv4nodejs` with `appium` without seeing it's a new major version that may be incompatible.
By the way, is there a migration guide for `opencv4nodejs` from 4.x to 5.x ?

**Comment by justadudewhohacks** [comment]
The only real thing to consider when migrating is, that some properties of the wrapped classes might have different spelling now, e.g. they should now correspond directly to the underlying OpenCV property name. That's why the property "point" changed to "pt" with the release. 

Unfortunately  for some properties there might be some inconsistencies in the typing files. Do you want to open a PR fixing the name in the typing file? Also if you spot this issue with other classes feel free to tell me. :)

**Comment by KazuCocoa** [comment]
This has been fixed in https://github.com/appium/appium-support/pull/119
Next or the next release has this

thanks
